name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
   name: code linting
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Ruff
      run: |
        pip install ruff

    - name: Run Ruff Linter
      run: |
        # Check for linting issues
        ruff check . --output-format=github
        # Fail if any formatting issue is found
        ruff format --check .
 

  check-env-files:
    name: Check for .env and Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Search for .env Files
        run: |
          if find . -type f -name "*.env" | grep .env; then
            echo "❌ .env file detected. Failing the build."
            exit 1
          else
            echo "✅ No .env files detected."
          fi

  run-entrypoint:
    name: Test Python Entrypoint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project dependencies 
          pip install -r requirements.txt

      - name: Run Entrypoint 
        run: |
           export $(grep -v '^#' vars | xargs)
           python -c "import slack_main" || exit 1
